<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Evolutionist</AssemblyName>
    <RootNamespace>Evolutionist</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildProjectDirectory)\mod\plugins\</OutputPath>
    <RainWorldDir Condition="'$(RainWorldDir)' == ''">D:\Steam\steamapps\common\Rain World</RainWorldDir>
    <SlugBaseDir Condition="'$(SlugBaseDir)' == ''">D:\Steam\steamapps\workshop\content\312520\2933196558\newest\plugins</SlugBaseDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RainWorldDir)\RainWorld_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HOOKS-Assembly-CSharp">
      <HintPath>$(RainWorldDir)\BepInEx\plugins\HOOKS-Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(RainWorldDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(RainWorldDir)\BepInEx\core\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(RainWorldDir)\BepInEx\core\MonoMod.Utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RainWorldDir)\RainWorld_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SlugBase">
      <HintPath>$(SlugBaseDir)\SlugBase.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

